version: "3"
services:
  hub:
    image: seleniarm/hub:4.20
  chrome:
    image: seleniarm/node-chromium:4.20
    shm_size: '1g'
    depends_on:
    - hub
    deploy:
      replicas: 0
    env_file: .env
  firefox:
    image: seleniarm/node-firefox:4.20
    shm_size: '1g'
    depends_on:
    - hub
    deploy:
      replicas: 0
    env_file: .env