version: "3"
services:
  hub:
    image: seleniarm/hub:4.10
  chrome:
    image: seleniarm/node-chromium:4.10
    shm_size: '2g'
    depends_on:
    - hub
    deploy:
      replicas: 1
    env_file: .env
  firefox:
    image: seleniarm/node-firefox:4.10
    shm_size: '2g'
    depends_on:
    - hub
    deploy:
      replicas: 1
    env_file: .env